name: Tests

on:
  push:
    paths:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip check
        pipenv install
    - name: Lint with Flake8
      run: |
        pipenv run pip install flake8
        pipenv run flake8 --ignore E501 dags --benchmark -v
        pipenv run flake8 --ignore E501 scripts --benchmark -v
    - name: Confirm Black code compliance (psf/black)
      run: |
        pipenv pip install pytest-black
        pipenv run pytest dags --black -v
    - name: Test with Pytest
      run: |
        pipenv run pip install pytest
        pipenv run pytest
